name: Building on Windows with MSYS2

on:
  workflow_call:
    inputs:
      windows_image:
        description: 'Name of the Windows image.'
        required: false
        default: 'windows-latest'
        type: string
      runtime:
        description: 'MSYS2 runtime'
        required: true
        type: string
      backend:
        description: 'GHDL backend'
        required: true
        type: string
      windows_artifact:
        description: 'Name of the Windows build artifact.'
        required: true
        type: string

jobs:
  Build:
    name: Build GHDL on Windows Server + MSYS2
    runs-on: ${{ inputs.windows_image }}

    env:
      msys2_packages: "make"
      common_packages: "gcc:p gcc-ada:p diffutils:p"
      mcode_packages: ""
      llvm_packages: "llvm:p clang:p"

    defaults:
      run:
        shell: "msys2 {0}"

    steps:
      - name: ⏬ Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ghdl/ghdl

      - name: '🟦 Setup MSYS2 for ${{ inputs.runtime }}'
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ inputs.runtime }}
          update: true
          install: ${{ env.msys2_packages }}
          pacboy: ${{ env.common_packages }} ${{ env.mcode_packages }} ${{ env.llvm_packages }}

      - name: Check build environemnt
        run: |
          echo "which gnat:        $(which gnat) ($($(which gnat) --version))"
          echo "which gnatmake:    $(which gnatmake) ($($(which gnatmake) --version))"
          echo "which llvm-config: $(which llvm-config) ($($(which llvm-config) --version))"

      - name: Prepare build environemnt
        run: |
          mkdir -p build/${{ inputs.backend }}
          mkdir -p install

      - name: ⚙ Configure
        run: |
          cd build/${{ inputs.backend }}
          [ '${{ inputs.backend }}' == 'llvm' ] && LLVM_ARGS='--with-llvm-config' || unset LLVM_ARGS

          NPROC=$(nproc)
          GNATMAKE="gnatmake -j$NPROC" \
          MAKE="make -j$NPROC" \
          ../../configure --prefix=../../install $LLVM_ARGS

      - name: 🔨 Make
        run: |
          cd build/${{ inputs.backend }}
          make

      - name: 📋 Install
        run: |
          cd build/${{ inputs.backend }}
          make install

      - name: 📋 Write requirements file
        run: |
          cd install
          ls -lAh
          if [ '${{ inputs.runtime }}' == 'mingw64' ]; then
            MSYS2_PREFIX=mingw64/mingw-w64-x86_64
          elif [ '${{ inputs.runtime }}' == 'ucrt64' ]; then
            MSYS2_PREFIX=ucrt64/mingw-w64-ucrt-x86_64
          fi
          echo "${MSYS2_PREFIX}-gcc-ada" >> ${{ inputs.runtime }}.requirements
          if [ '${{ inputs.backend }}' == 'llvm' ]; then
           echo "${MSYS2_PREFIX}-llvm-libs" >> ${{ inputs.runtime }}.requirements
          fi

      - name: Run 'sanity' from testsuite
        run: |
          export GHDL=$(pwd)/install/bin/ghdl
          cd testsuite

          # no pyunit
          ./testsuite.sh sanity

      - name: 📤 Upload '${{ inputs.windows_artifact }}-${{ inputs.runtime }}-${{ inputs.backend }}' artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.windows_artifact }}-${{ inputs.runtime }}-${{ inputs.backend }}
          path: ./install
          if-no-files-found: error
          retention-days: 1

  Test:
    name: Test GHDL on Windows Server + MSYS2
    runs-on: ${{ inputs.windows_image }}
    needs:
      - Build

    env:
      common_packages: "diffutils:p"

    defaults:
      run:
        shell: "msys2 {0}"

    steps:
      - name: ⏬ Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ghdl/ghdl

      - name: '🟦 Setup MSYS2 for ${{ inputs.runtime }}'
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ inputs.runtime }}
          update: true
          pacboy: ${{ env.common_packages }}

      - name: 📥 Download artifacts '${{ inputs.windows_artifact }}-${{ inputs.runtime }}-${{ inputs.backend }}' from 'Build' job
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.windows_artifact }}-${{ inputs.runtime }}-${{ inputs.backend }}
          path: install

      - name: Install GHDL (chmod) and prepare test environment
        run: |
          chmod +x ./install/bin/*
          xargs -r -a ./install/${{ inputs.runtime }}.requirements pacman -S --noconfirm
          echo "PATH=$(pwd)/install/bin:$PATH" >> $GITHUB_ENV
          cat $GITHUB_ENV

      - name: Version check
        run: |
          echo "PATH=$PATH"
          export PATH=$(pwd)/install/bin:$PATH
          echo "which ghdl: $(which ghdl)"
          ghdl version

      - name: Run tests in testsuite
        run: |
          export PATH=$(pwd)/install/bin:$PATH
          cd testsuite

          # no pyunit
          ./testsuite.sh sanity gna vests synth vpi vhpi

  Package:
    name: Package GHDL on Windows Server + MSYS2
    runs-on: windows-latest
    needs:
      - Build

    env:
      msys2_packages: ""
      common_packages: ""
      mcode_packages: ""
      llvm_packages: "llvm:p"

    defaults:
      run:
        shell: "msys2 {0}"

    steps:
      - name: ⏬ Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ghdl/ghdl

      - name: '🟦 Setup MSYS2 for ${{ inputs.runtime }}'
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ inputs.runtime }}
          update: true
          install: ${{ env.msys2_packages }}
          pacboy: "${{ env.common_packages }} ${{ env.mcode_packages }} ${{ env.llvm_packages }}"

  Install:
    name: Install and Test GHDL on Windows Server + MSYS2
    runs-on: windows-latest
    needs:
      - Package

    defaults:
      run:
        shell: "msys2 {0}"

    steps:
      - name: ⏬ Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ghdl/ghdl

      - name: '🟦 Setup MSYS2 for ${{ inputs.runtime }}'
        uses: msys2/setup-msys2@v2
        with:
          update: true
