name: Building on Ubuntu 24.04 (Matrix)

on:
  workflow_call:
    inputs:
      jobs:
        description: 'JSON list with environment fields, naming the system and backend for compilation.'
        required: true
        type: string
      ubuntu_image:
        description: 'Name of the Ubuntu image.'
        required: false
        default: 'ubuntu-24.04'
        type: string
      ubuntu_artifact:
        description: 'Name of the Ubuntu build artifact.'
        required: true
        type: string

jobs:
  Build:
    name: Build GHDL on Ubuntu 2024.04 (LTS)
    runs-on: ${{ inputs.ubuntu_image }}

    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(inputs.jobs) }}

    defaults:
      run:
        shell: bash

    steps:
      - name: ⏬ Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ghdl/ghdl

      - name: 🔧 Install dependencies
        run: |
          [ '${{ matrix.backend }}' == 'llvm' ] && LLVM_ARGS='llvm clang' || unset LLVM_ARGS
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends gcc g++ gnat $LLVM_ARGS

      - name: Prepare build environment
        run: |
          mkdir -p build/${{ matrix.backend }}
          ./configure --help

      - name: ⚙ Configure
        run: |
          cd build/${{ matrix.backend }}
          [ '${{ matrix.backend }}' == 'llvm' ] && LLVM_ARGS='--with-llvm-config' || unset LLVM_ARGS

          NPROC=$(nproc)
          GNATMAKE="gnatmake -j$NPROC" \
          MAKE="make -j$NPROC" \
          ../../configure --prefix=../../install $LLVM_ARGS

      - name: 🔨 Make
        run: |
          cd build/${{ matrix.backend }}
          make

      - name: 📋 Install
        run: |
          cd build/${{ matrix.backend }}
          sudo make install

      - name: 📤 Upload '${{ inputs.ubuntu_artifact }}-24.04-x86_64-${{ matrix.backend }}' artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.ubuntu_artifact }}-24.04-x86_64-${{ matrix.backend }}
          path: ./install
          if-no-files-found: error
          retention-days: 1

  Test:
    name: Test GHDL on Ubuntu 2024.04 (LTS)
    runs-on: ${{ inputs.ubuntu_image }}
    needs:
      - Build

    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(inputs.jobs) }}

    defaults:
      run:
        shell: bash

    steps:
      - name: ⏬ Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ghdl/ghdl

      - name: 📥 Download artifacts '${{ inputs.ubuntu_artifact }}-24.04-x86_64-${{ matrix.backend }}' from 'Build' job
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.ubuntu_artifact }}-24.04-x86_64-${{ matrix.backend }}
          path: install

      - name: Install GHDL (chmod) and prepare test environment
        run: |
          chmod +x ./install/bin/*
          echo "PATH=$(pwd)/install/bin:$PATH" >> $GITHUB_ENV

      - name: Sanity checks
        run: |
          echo "PATH:       $PATH"
          echo "which ghdl: $(which ghdl)"
          ghdl version

      - name: Run tests in testsuite
        run: |
          cd testsuite

          # no pyunit
          ./testsuite.sh sanity gna vests synth vpi vhpi
