name: Building on Ubuntu 24.04 (Matrix)

on:
  workflow_call:
    inputs:
      ubuntu_image:
        description: 'Name of the Ubuntu image.'
        required: false
        default: 'ubuntu-24.04'
        type: string
      backend:
        description: 'GHDL backend'
        required: true
        type: string
      ubuntu_artifact:
        description: 'Name of the Ubuntu build artifact.'
        required: true
        type: string

jobs:
  Build:
    name: Build GHDL on Ubuntu 2024.04 (LTS)
    runs-on: ${{ inputs.ubuntu_image }}

    defaults:
      run:
        shell: bash

    steps:
      - name: ⏬ Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ghdl/ghdl

      - name: 🔧 Install dependencies
        run: |
          [ '${{ inputs.backend }}' == 'llvm' ] && LLVM_ARGS='llvm clang' || unset LLVM_ARGS
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends gcc g++ gnat $LLVM_ARGS

      - name: Prepare build environment
        run: |
          mkdir -p build/${{ inputs.backend }}
          ./configure --help

      - name: ⚙ Configure
        run: |
          cd build/${{ inputs.backend }}
          [ '${{ inputs.backend }}' == 'llvm' ] && LLVM_ARGS='--with-llvm-config' || unset LLVM_ARGS

          NPROC=$(nproc)
          GNATMAKE="gnatmake -j$NPROC" \
          MAKE="make -j$NPROC" \
          ../../configure --prefix=../../install $LLVM_ARGS

      - name: 🔨 Make
        run: |
          cd build/${{ inputs.backend }}
          make

      - name: 📋 Install
        run: |
          cd build/${{ inputs.backend }}
          sudo make install

      - name: 📋 Write requirements file
        run: |
          ls -lAh
          echo "libgnat-13" >> ubuntu.requirements
          if [ '${{ inputs.backend }}' == 'llvm' ]; then
            echo "libllvm18" >> ubuntu.requirements
          fi
          sudo cp ubuntu.requirements ./install

      - name: Run 'sanity' from testsuite
        run: |
          export GHDL=$(pwd)/install/bin/ghdl
          cd testsuite

          # no pyunit
          ./testsuite.sh sanity

      - name: 📤 Upload '${{ inputs.ubuntu_artifact }}-24.04-x86_64-${{ inputs.backend }}' artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.ubuntu_artifact }}-24.04-x86_64-${{ inputs.backend }}
          path: ./install
          if-no-files-found: error
          retention-days: 1

  Test:
    name: Test GHDL on Ubuntu 2024.04 (LTS)
    runs-on: ${{ inputs.ubuntu_image }}
    needs:
      - Build

    defaults:
      run:
        shell: bash

    steps:
      - name: ⏬ Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ghdl/ghdl

      - name: 📥 Download artifacts '${{ inputs.ubuntu_artifact }}-24.04-x86_64-${{ inputs.backend }}' from 'Build' job
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.ubuntu_artifact }}-24.04-x86_64-${{ inputs.backend }}
          path: install

      - name: Install GHDL (chmod) and prepare test environment
        run: |
          chmod +x ./install/bin/*
          sudo xargs -r -a ./install/ubuntu.requirements apt-get install -y --no-install-recommends
          echo "PATH=$(pwd)/install/bin:$PATH" >> $GITHUB_ENV

      - name: Version check
        run: |
          echo "which ghdl: $(which ghdl)"
          ghdl version

      - name: Run tests in testsuite
        run: |
          cd testsuite

          # no pyunit
          ./testsuite.sh sanity gna vests synth vpi vhpi
