name: Package GHDL as Docker Image

on:
  workflow_call:
    inputs:
      ubuntu_image:
        description: 'Name of the Ubuntu image.'
        required: false
        default: 'ubuntu-24.04'
        type: string
      base_image:
        description: 'Name of Docker base-image.'
        required: true
        type: string
      ghdl_artifact:
        description: 'Name of the GHDL artifact.'
        required: true
        type: string

jobs:
  Ubuntu:
    name: Package GHDL as Docker Image
    runs-on: ${{ inputs.ubuntu_image }}

    defaults:
      run:
        shell: bash

    steps:
      - name: ⏬ Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ghdl/ghdl

      - name: 📥 Download artifacts '${{ inputs.ghdl_artifact }}' from 'Build' job
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.ghdl_artifact }}
          path: install
