name: Packaging pyGHDL with libghdl (standalone)

on:
  workflow_call:
    inputs:
      os:
        description: 'Name of the OS.'
        required: true
        type: string
      os_image:
        description: 'Name of the OS image.'
        required: true
        type: string
      runtime:
        description: 'Name of the MSYS2 runtime.'
        required: false
        default: ''
        type: string
      backend:
        description: 'Name of the GHDL backend.'
        required: true
        type: string
      jobs:
        description: 'JSON list with environment fields, naming the system and backend for compilation.'
        required: true
        type: string
      libghdl_artifact:
        description: 'Name of the libghdl artifact.'
        required: true
        type: string
      pyghdl_artifact:
        description: 'Name of the pyghdl artifact.'
        required: true
        type: string

jobs:
  Package:
    name: '🐍 Package pyGHDL for ${{ inputs.os }} and Python ${{ matrix.python_version }}'
    runs-on: ${{ inputs.os_image }}

    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(inputs.jobs) }}

    steps:
      - name: Assemble artifact name
        id: artifact_name
        run: |
          echo "pyghdl_artifact=${{ inputs.pyghdl_artifact }}-py${{ matrix.python_version }}" >> $env:GITHUB_OUTPUT

      - name: '🧰 Checkout'
        uses: actions/checkout@v4

      - name: '🐍 Setup Python'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}

      - name: '🔧 Install dependencies'
        run: |
          python -m pip install --disable-pip-version-check "pyTooling[packaging]" wheel

      - name: 📥 Download artifacts '${{ inputs.libghdl_artifact }}-${{ inputs.backend }}' from 'Build' job
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.libghdl_artifact }}-${{ inputs.backend }}
          path: install

      - name: Copy libghdl files
        run: |
          cp -Recurse install/lib pyGHDL

      - name: 🔨 Build Python package (binary distribution - wheel)
        run: python setup.py bdist_wheel

#      - name: Debug
#        run: |
#          tree /F /A pyGHDL
#          tree /F /A dist
#          tar -tf dist\pyGHDL*.whl

      - name: '📤 Upload artifact: ${{ steps.artifact_name.outputs.pyghdl_artifact }}'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact_name.outputs.pyghdl_artifact }}
          path: dist/pyGHDL*.whl
          if-no-files-found: error

  Test:
    name: '🐍 Test pyGHDL on ${{ inputs.os }} and Python ${{ matrix.python_version }}'
    runs-on: ${{ inputs.os_image }}

    needs:
      - Package

    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(inputs.jobs) }}

    steps:
      - name: Assemble artifact name
        id: artifact_name
        run: |
          echo "pyghdl_artifact=${{ inputs.pyghdl_artifact }}-py${{ matrix.python_version }}" >> $env:GITHUB_OUTPUT

      - name: '🧰 Checkout'
        uses: actions/checkout@v4

      - name: '🐍 Setup Python'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}

      - name: 📥 Download artifacts '${{ steps.artifact_name.outputs.pyghdl_artifact }}' from 'Package' job
        uses: actions/download-artifact@v4
        with:
          name: ${{ steps.artifact_name.outputs.pyghdl_artifact }}
          path: wheels

      - name: '🔧 Install dependencies'
        run: |
          python -m pip install --disable-pip-version-check (Get-Item .\wheels\pyGHDL-*.whl).FullName
