# GitHub Actions does not properly support variables in YAML files.
# As a workaround, a job can be used to produce output parameters,
# which can be referenced by other jobs.

name: Parameters

on:
  workflow_call:
    inputs:
      ubuntu_image:
        description: 'Name of the Ubuntu image.'
        required: false
        default: 'ubuntu-24.04'
        type: string
      package_name:
        description: 'Base-name of all GHDL artifacts.'
        required: true
        type: string
      library_name:
        description: 'Base-name of all libghdl artifacts.'
        required: true
        type: string
      testsuites:
        description: "List of GHDL testsuites to execute while testing (space separated). Alternatively: 'all' or 'none'"
        required: false
        default: 'all'
        type: string

    outputs:
      ghdl_basename:
        description: "Artifact basename for GHDL."
        value: ${{ inputs.package_name }}
      libghdl_basename:
        description: "Artifact basename for libghdl."
        value: ${{ inputs.library_name }}
      testsuites:
        description: "List of GHDL testsuites to execute while testing (space separated)."
        value: ${{ jobs.Parameters.outputs.testsuites }}

jobs:
  Parameters:
    runs-on: ${{ inputs.ubuntu_image }}
    outputs:
      testsuites: ${{ steps.params.outputs.testsuites }}

    steps:
      - name: Generate 'params' and 'python_jobs'
        id: params
        run: |
          if [ '${{ inputs.testsuites }}' == 'all' ]; then
            echo "testsuites=sanity gna vests synth vpi vhpi" >> $GITHUB_OUTPUT
          else
            echo "testsuites=${{ inputs.testsuites }}" >> $GITHUB_OUTPUT
          fi
