name: Build, Package and Test GHDL

on:
  push:
  pull_request:

jobs:
# Building
#   Ubuntu (x86-64)
#     mcode + GPL
#     gcc
#   macOS (x86-64)
#     mcode
#     llvm
#     llvm-jit
#   macOS (aarch64)
#     llvm
#     llvm-jit
#   Windows (x86-64)
#     MinGW64
#       llvm-jit
#     UCRT64
#       llvm-jit

# Windows Standalone - ZIP
#   UCRT64 - mcode
#   UCRT64 - llvm

# Sanity Check Windows Standalone
#   simple simulation

# pyGHDL wheel
#   Python 3.10
#     Windows
#     Linux
#     macOS
#   Python 3.11
#     Windows
#     Linux
#     macOS
#   Python 3.12
#     Windows
#     Linux
#     macOS

# Python code coverage
# Publish results
# Python test results
#   merge

# Sanity Check pyGHDL
#

# Release Page (on tag)
#   Assets

#

  Params:
    uses: ./.github/workflows/Parameters.yml
    with:
      name:       "ghdl"
      testsuites: "sanity"         # disable parameter to fall back to 'all'

  Ubuntu:
    uses: ./.github/workflows/Build-Ubuntu.yml
    needs:
      - Params
    strategy:
      fail-fast: false
      matrix:
        include:
          - {'icon': '🐧🟨', 'backend': 'mcode',    'ubuntu_image': 'ubuntu-22.04', 'testsuites': '${{ needs.Params.outputs.testsuites }}'}  # 'all', 'none' or list of testsuites
          - {'icon': '🐧🟨', 'backend': 'llvm',     'ubuntu_image': 'ubuntu-22.04', 'testsuites': '${{ needs.Params.outputs.testsuites }}'}  # 'all', 'none' or list of testsuites
          - {'icon': '🐧🟨', 'backend': 'llvm-jit', 'ubuntu_image': 'ubuntu-22.04', 'testsuites': '${{ needs.Params.outputs.testsuites }}'}  # 'all', 'none' or list of testsuites
          - {'icon': '🐧🟨', 'backend': 'gcc',      'ubuntu_image': 'ubuntu-22.04', 'testsuites': '${{ needs.Params.outputs.testsuites }}' }    # 'all', 'none' or list of testsuites
          - {'icon': '🐧🟩', 'backend': 'mcode',    'ubuntu_image': 'ubuntu-24.04', 'testsuites': '${{ needs.Params.outputs.testsuites }}'}  # 'all', 'none' or list of testsuites
          - {'icon': '🐧🟩', 'backend': 'llvm',     'ubuntu_image': 'ubuntu-24.04', 'testsuites': '${{ needs.Params.outputs.testsuites }}'}  # 'all', 'none' or list of testsuites
          - {'icon': '🐧🟩', 'backend': 'llvm-jit', 'ubuntu_image': 'ubuntu-24.04', 'testsuites': '${{ needs.Params.outputs.testsuites }}'}  # 'all', 'none' or list of testsuites
          - {'icon': '🐧🟩', 'backend': 'gcc',      'ubuntu_image': 'ubuntu-24.04', 'testsuites': 'all' }                                    # 'all', 'none' or list of testsuites
    with:
      ubuntu_image:    ${{ matrix.ubuntu_image }}
      backend:         ${{ matrix.backend }}
      testsuites:      ${{ matrix.testsuites }}
      ubuntu_artifact: ${{ needs.Params.outputs.basename }}-${{ matrix.ubuntu_image }}-x86_64
      html_artifact:  'documentation-html'
      latex_document: 'ghdl'
      latex_artifact: 'documentation-latex'
      pdf_artifact:   'documentation-pdf'

  macOS:
    uses: ./.github/workflows/Build-MacOS.yml
    needs:
      - Params
    strategy:
      fail-fast: false
      matrix:
        include:
          - {'icon': '🍎🟧', 'backend': 'mcode',    'macos_image': 'macos-12', 'gnat_arch': 'x86_64',  'gnat_version': '14.1.0-3', 'testsuites': '${{ needs.Params.outputs.testsuites }}'}  # 'all', 'none' or list of testsuites
          - {'icon': '🍎🟧', 'backend': 'llvm',     'macos_image': 'macos-12', 'gnat_arch': 'x86_64',  'gnat_version': '14.1.0-3', 'testsuites': '${{ needs.Params.outputs.testsuites }}'}  # 'all', 'none' or list of testsuites
          - {'icon': '🍎🟨', 'backend': 'mcode',    'macos_image': 'macos-13', 'gnat_arch': 'x86_64',  'gnat_version': '14.1.0-3', 'testsuites': '${{ needs.Params.outputs.testsuites }}'}  # 'all', 'none' or list of testsuites
          - {'icon': '🍎🟨', 'backend': 'llvm',     'macos_image': 'macos-13', 'gnat_arch': 'x86_64',  'gnat_version': '14.1.0-3', 'testsuites': '${{ needs.Params.outputs.testsuites }}'}  # 'all', 'none' or list of testsuites
###       - {'icon': '🍏🟩', 'backend': 'mcode',    'macos_image': 'macos-14', 'gnat_arch': 'aarch64', 'gnat_version': '14.1.0-3', 'testsuites': 'none'}                                    # mcode not yet supported for aarch64
          - {'icon': '🍏🟩', 'backend': 'llvm',     'macos_image': 'macos-14', 'gnat_arch': 'aarch64', 'gnat_version': '14.1.0-3', 'testsuites': '${{ needs.Params.outputs.testsuites }}'}  # 'all', 'none' or list of testsuites
          - {'icon': '🍏🟩', 'backend': 'llvm-jit', 'macos_image': 'macos-14', 'gnat_arch': 'aarch64', 'gnat_version': '14.1.0-3', 'testsuites': '${{ needs.Params.outputs.testsuites }}'}  # 'all', 'none' or list of testsuites
    with:
      macos_image:    ${{ matrix.macos_image }}
      gnat_arch:      ${{ matrix.gnat_arch }}
      gnat_version:   ${{ matrix.gnat_version }}
      backend:        ${{ matrix.backend }}
      testsuites:     ${{ matrix.testsuites }}
      macos_artifact: ${{ needs.Params.outputs.basename }}-${{ matrix.macos_image }}-${{ matrix.gnat_arch }}

  Windows:
    uses: ./.github/workflows/Build-MSYS2.yml
    needs:
      - Params
    strategy:
      fail-fast: false
      matrix:
        include:
###       - {'icon': '🪟', 'backend': 'mcode',    'runtime': 'mingw32', 'testsuites': '${{ needs.Params.outputs.testsuites }}'}  # No gcc-ada package for MinGW32, support was dropped
          - {'icon': '🪟', 'backend': 'mcode',    'runtime': 'mingw64', 'testsuites': '${{ needs.Params.outputs.testsuites }}'}
          - {'icon': '🪟', 'backend': 'llvm',     'runtime': 'mingw64', 'testsuites': 'sanity gna synth vpi vhpi'}                # no vests (too slow)
          - {'icon': '🪟', 'backend': 'llvm-jit', 'runtime': 'mingw64', 'testsuites': 'sanity gna synth vpi vhpi'}                # no vests (too slow)
          - {'icon': '🪟', 'backend': 'mcode',    'runtime': 'ucrt64',  'testsuites': '${{ needs.Params.outputs.testsuites }}'}
          - {'icon': '🪟', 'backend': 'llvm',     'runtime': 'ucrt64',  'testsuites': 'sanity gna synth vpi vhpi'}                # no vests (too slow)
          - {'icon': '🪟', 'backend': 'llvm-jit', 'runtime': 'ucrt64',  'testsuites': 'sanity gna synth vpi vhpi'}                # no vests (too slow)
    with:
      runtime:          ${{ matrix.runtime }}
      backend:          ${{ matrix.backend }}
      testsuites:       ${{ matrix.testsuites }}
      windows_artifact: ${{ needs.Params.outputs.basename }}-windows
      pacman_artifact:  ''

  Docker:
    uses: ./.github/workflows/Image-Docker.yml
    needs:
      - Params
      - Ubuntu
    strategy:
      fail-fast: false
      matrix:
        include:
          - {'base_image': 'ubuntu:24.04', 'ghdl_artifact': '${{ needs.Params.outputs.basename }}-ubuntu-24.04-x86_64-llvm'}
          - {'base_image': 'debian:slim',  'ghdl_artifact': '${{ needs.Params.outputs.basename }}-ubuntu-24.04-x86_64-llvm'}
    with:
      base_image:    ${{ matrix.base_image }}
      ghdl_artifact: ${{ matrix.ghdl_artifact }}

  Standalone:
    uses: ./.github/workflows/Package-Windows.yml
    needs:
      - Windows
    strategy:
      fail-fast: false
      matrix:
        include:
          - {'ghdl_artifact': '${{ needs.Params.outputs.basename }}-windows-ucrt64-mcode'}
          - {'ghdl_artifact': '${{ needs.Params.outputs.basename }}-windows-ucrt64-llvm'}
    with:
      ghdl_artifact: ${{ matrix.ghdl_artifact }}

  Python:
    uses: ./.github/workflows/Build-pyGHDL.yml
    with:
      black: false

  pyGHDL:
    uses: ./.github/workflows/Package-pyGHDL.yml
    needs:
      - Ubuntu
      - Windows
      - Python
    with:
      jobs: |
        [
          {'pyicon': '🟡', 'os': 'Ubuntu',  'os_image': 'ubuntu-24.04',   'backend': 'mcode',                      'ghdl_artifact': '${{ needs.Params.outputs.basename }}-ubuntu-24.04-x86_64-mcode', 'python_version': '3.10'},
          {'pyicon': '🟢', 'os': 'Ubuntu',  'os_image': 'ubuntu-24.04',   'backend': 'mcode',                      'ghdl_artifact': '${{ needs.Params.outputs.basename }}-ubuntu-24.04-x86_64-mcode', 'python_version': '3.11'},
          {'pyicon': '🟢', 'os': 'Ubuntu',  'os_image': 'ubuntu-24.04',   'backend': 'mcode',                      'ghdl_artifact': '${{ needs.Params.outputs.basename }}-ubuntu-24.04-x86_64-mcode', 'python_version': '3.12'},
          {'pyicon': '🟡', 'os': 'Windows', 'os_image': 'windows-latest', 'backend': 'mcode', 'runtime': 'ucrt64', 'ghdl_artifact': '${{ needs.Params.outputs.basename }}-windows-ucrt64-mcode',      'python_version': '3.10'},
          {'pyicon': '🟢', 'os': 'Windows', 'os_image': 'windows-latest', 'backend': 'mcode', 'runtime': 'ucrt64', 'ghdl_artifact': '${{ needs.Params.outputs.basename }}-windows-ucrt64-mcode',      'python_version': '3.11'},
          {'pyicon': '🟢', 'os': 'Windows', 'os_image': 'windows-latest', 'backend': 'mcode', 'runtime': 'ucrt64', 'ghdl_artifact': '${{ needs.Params.outputs.basename }}-windows-ucrt64-mcode',      'python_version': '3.12'}
        ]
      python_version: '3.12'

#  GNATdoc:
#    uses: ./.github/workflows/Documentation-GNAT.yml
#    with:
#      ubuntu_image:  "ubuntu-20.04"            # gnat-gps (incl. GNATdoc) is limited to Ubuntu 20.04
#      html_artifact: "documentation-gnatdoc"


  PublishToGitHubPages:
    needs:
#      - GNATdoc
      - Ubuntu
    uses: ./.github/workflows/Publish-GitHubPages.yml

  Nightly:
    runs-on: ubuntu-24.04
    needs:
      - Ubuntu
      - macOS
      - Windows
      - Docker
      - Standalone
      - PublishToGitHubPages
      - pyGHDL
    steps:
      - name: "Dummy"
        run: echo "Dummy"

  Release:
    runs-on: ubuntu-24.04
    needs:
      - Ubuntu
      - macOS
      - Windows
      - Docker
      - Standalone
      - PublishToGitHubPages
      - pyGHDL
    steps:
      - name: "Dummy"
        run: echo "Dummy"
