name: Build, Package and Test GHDL

on:
  push:
  pull_request:

jobs:
# Building
#   Ubuntu (x86-64)
#     mcode
#     mcode + GPL
#     llvm
#     llvm-jit
#     gcc
#   macOS (x86-64)
#     mcode
#     llvm
#     llvm-jit
#   macOS (aarch64)
#     llvm
#     llvm-jit
#   Windows (x86-64)
#     MinGW64
#       mcode
#       llvm
#       llvm-jit
#     UCRT64
#       mcode
#       llvm
#       llvm-jit

# Documentation
#   GNAT
#   Sphinx
#     HTML
#     LaTeX
#     man
#   PDF

# Testing from artifact
#   Ubuntu - mcode
#   Ubuntu - llvm
#   Ubuntu - gcc
#   macOS -  llvm
#   UCRT64 - llvm

# Windows Standalone - ZIP
#   UCRT64 - mcode
#   UCRT64 - llvm

# Sanity Check Windows Standalone
#   simple simulation

# pyGHDL wheel
#   Python 3.10
#     Windows
#     Linux
#     macOS
#   Python 3.11
#     Windows
#     Linux
#     macOS
#   Python 3.12
#     Windows
#     Linux
#     macOS

# Python code coverage
# Publish results
# Python test results
#   merge

# Sanity Check pyGHDL
#

# Release Page (on tag)
#   Assets

#

  Ubuntu:
    uses: ./.github/workflows/Build-Ubuntu.yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - {'icon': 'x', 'backend': 'mcode', 'testsuites': 'none'}  # 'all', 'none' or list of testsuites
#          - {'icon': 'y', 'backend': 'llvm',  'testsuites': 'none'}  # 'all', 'none' or list of testsuites
    with:
      backend: ${{ matrix.backend }}
      testsuites: ${{ matrix.testsuites }}
      ubuntu_artifact: ghdl-ubuntu
      html_artifact:  '' # 'documentation-html'
      latex_document: 'ghdl'
      latex_artifact: '' # 'documentation-latex'
      pdf_artifact:   '' # 'documentation-pdf'

#  macOS:
#    uses: ./.github/workflows/Build-MacOS.yml
#    with:
#      jobs: "[{'icon': 'x', 'backend': 'llvm', 'testsuites': 'none'}]"
##      jobs: |
##        [
##          {'icon': 'x', 'backend': 'mcode', 'testsuites': 'all'},
##          {'icon': 'y', 'backend': 'llvm',  'testsuites': 'all'}
##        ]
##      testsuites: ${{ matrix.testsuites }}
#      macos_artifact: ghdl-macos

  Windows:
    uses: ./.github/workflows/Build-MSYS2.yml
    strategy:
      fail-fast: false
      matrix:
        include:
#          - {'icon': 'Mx', 'runtime': 'mingw64', 'backend': 'mcode', 'testsuites': 'none'}  # 'all', 'none' or list of testsuites
#          - {'icon': 'My', 'runtime': 'mingw64', 'backend': 'llvm',  'testsuites': 'none'}  # sanity gna vpi vhpi'}    # no vests
          - {'icon': 'Ux', 'runtime': 'ucrt64',  'backend': 'mcode', 'testsuites': 'none'}  # 'all', 'none' or list of testsuites
#          - {'icon': 'Uy', 'runtime': 'ucrt64',  'backend': 'llvm',  'testsuites': 'none'}  # sanity gna vpi vhpi'}    # no vests, synth
    with:
      runtime: ${{ matrix.runtime }}
      backend: ${{ matrix.backend }}
      testsuites: ${{ matrix.testsuites }}
      windows_artifact: ghdl-windows
      pacman_artifact:  ''

  Python:
    uses: ./.github/workflows/Build-pyGHDL.yml
    with:
      black: false

  pyGHDL:
    uses: ./.github/workflows/Package-pyGHDL.yml
    needs:
      - Ubuntu
      - Windows
      - Python
    with:
      jobs: |
        [
          {'pyicon': '游리', 'os': 'Ubuntu',  'os_image': 'ubuntu-24.04',   'backend': 'mcode',                      'ghdl_artifact': 'ghdl-ubuntu-24.04-x86_64-mcode', 'python_version': '3.10'},
          {'pyicon': '游릭', 'os': 'Ubuntu',  'os_image': 'ubuntu-24.04',   'backend': 'mcode',                      'ghdl_artifact': 'ghdl-ubuntu-24.04-x86_64-mcode', 'python_version': '3.11'},
          {'pyicon': '游릭', 'os': 'Ubuntu',  'os_image': 'ubuntu-24.04',   'backend': 'mcode',                      'ghdl_artifact': 'ghdl-ubuntu-24.04-x86_64-mcode', 'python_version': '3.12'},
          {'pyicon': '游리', 'os': 'Windows', 'os_image': 'windows-latest', 'backend': 'mcode', 'runtime': 'ucrt64', 'ghdl_artifact': 'ghdl-windows-ucrt64-mcode',      'python_version': '3.10'},
          {'pyicon': '游릭', 'os': 'Windows', 'os_image': 'windows-latest', 'backend': 'mcode', 'runtime': 'ucrt64', 'ghdl_artifact': 'ghdl-windows-ucrt64-mcode',      'python_version': '3.11'},
          {'pyicon': '游릭', 'os': 'Windows', 'os_image': 'windows-latest', 'backend': 'mcode', 'runtime': 'ucrt64', 'ghdl_artifact': 'ghdl-windows-ucrt64-mcode',      'python_version': '3.12'}
        ]
      python_version: '3.12'



#  GNATdoc:
#    uses: ./.github/workflows/Documentation-GNAT.yml
#

  PublishToGitHubPages:
    needs:
#      - GNATdoc
      - Ubuntu
    uses: ./.github/workflows/Publish-GitHubPages.yml

  Nightly:
    runs-on: ubuntu-24.04
    needs:
      - Ubuntu
#      - macOS
      - Windows
      - PublishToGitHubPages
      - pyGHDL
    steps:
      - name: "Dummy"
        run: echo "Dummy"

  Release:
    runs-on: ubuntu-24.04
    needs:
      - Ubuntu
#      - macOS
      - Windows
      - PublishToGitHubPages
      - pyGHDL
    steps:
      - name: "Dummy"
        run: echo "Dummy"
