name: Build, Package and Test GHDL

on:
  push:
  pull_request:

jobs:
# Building
#   Ubuntu (x86-64)
#     mcode
#     mcode + GPL
#     llvm
#     llvm-jit
#     gcc
#   macOS (x86-64)
#     mcode
#     llvm
#     llvm-jit
#   macOS (aarch64)
#     llvm
#     llvm-jit
#   Windows (x86-64)
#     MinGW64
#       mcode
#       llvm
#       llvm-jit
#     UCRT64
#       mcode
#       llvm
#       llvm-jit

# Documentation
#   GNAT
#   Sphinx
#     HTML
#     LaTeX
#     man
#   PDF

# Testing from artifact
#   Ubuntu - mcode
#   Ubuntu - llvm
#   Ubuntu - gcc
#   macOS -  llvm
#   UCRT64 - llvm

# Windows Standalone - ZIP
#   UCRT64 - mcode
#   UCRT64 - llvm

# Sanity Check Windows Standalone
#   simple simulation

# pyGHDL wheel
#   Python 3.10
#     Windows
#     Linux
#     macOS
#   Python 3.11
#     Windows
#     Linux
#     macOS
#   Python 3.12
#     Windows
#     Linux
#     macOS

# Python code coverage
# Publish results
# Python test results
#   merge

# Sanity Check pyGHDL
#

# Release Page (on tag)
#   Assets

#

  Ubuntu:
    uses: ./.github/workflows/Build-Ubuntu.yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - {'icon': 'x', 'backend': 'mcode'}
          - {'icon': 'y', 'backend': 'llvm' }
    with:
      backend: ${{ matrix.backend }}
      ubuntu_artifact: ghdl-ubuntu
      html_artifact: 'documentation-html'
      latex_document: 'GHDL'
      latex_artifact: 'documentation-latex'
      pdf_artifact: 'documentation-pdf'

  macOS:
    uses: ./.github/workflows/Build-MacOS.yml
    with:
      jobs: "[{'icon': 'x', 'backend': 'llvm'}]"
#      jobs: |
#        [
#          {'icon': 'x', 'backend': 'mcode'},
#          {'icon': 'y', 'backend': 'llvm' }
#        ]
      macos_artifact: ghdl-macos

  Windows:
    uses: ./.github/workflows/Build-MSYS2.yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - {'icon': 'Mx', 'runtime': 'mingw64', 'backend': 'mcode'}
          - {'icon': 'My', 'runtime': 'mingw64', 'backend': 'llvm' }
          - {'icon': 'Ux', 'runtime': 'ucrt64',  'backend': 'mcode'}
          - {'icon': 'Uy', 'runtime': 'ucrt64',  'backend': 'llvm' }
    with:
      runtime: ${{ matrix.runtime }}
      backend: ${{ matrix.backend }}
      windows_artifact: ghdl-windows

  Python:
    uses: ./.github/workflows/Build-pyGHDL.yml

#  GNATdoc:
#    uses: ./.github/workflows/Documentation-GNAT.yml
#

  PublishToGitHubPages:
    needs:
#      - GNATdoc
      - Ubuntu
    uses: ./.github/workflows/Publish-GitHubPages.yml

  Release:
    runs-on: ubuntu-24.04
    needs:
      - Ubuntu
      - macOS
      - Windows
      - Python
      - PublishToGitHubPages
    steps:
      - name: "Dummy"
        run: echo "Dummy"
